### ISSUE TITLE
updates to obo resource files breaks sherlok parsing

### ISSUE THREAD

**Issue by stripathy** [renaud/neuroNER#58]
@renaud the commits that you and @tgbugs have made to the .obo resource files have broken the sherlok pipelines so that the simple process of reimporting the most up-to-date resource files from the github repo using the "clean" method no longer works.

Moving forward we'll need to have some way of ensuring that the changes to the .obo files doesn't break the sherlok infrastructure.

**Comment by tgbugs** [comment]
@stripathy pretty much everything I did was cosmetic (so that it would work in my parser), if the issue happens on the obo files that are generated from robo files then there's not issue deleting them. If the issue happens on the obo files that are not generated from robo files let me know and I can take a look.

**Comment by renaud** [comment]
```
Caused by: java.lang.NullPointerException: null
    at org.apache.uima.ruta.action.MarkTableAction.execute(MarkTableAction.java:111) ~[ruta-core-2.3.1.jar:2.3.1]
    at org.apache.uima.ruta.rule.AbstractRuleElement.apply(AbstractRuleElement.java:132) ~[ruta-core-2.3.1.jar:2.3.1]
```
